services:
  db:
    image: mysql:8.0
    container_name: mysgym_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gimnasio
    ports:
      - "3310:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./database_schema.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  mysqldata:
